[package]
name = "spectrum_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.0"
midi_encoder = { path = "../midi_encoder" }
audio_to_spectrum = { path = "../audio_to_spectrum" }